services:
  db:
    image: postgres:18.0
    environment:
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_USER=zeno
      - POSTGRES_DB=zeno
    ports:
      - ${DB_PORT}:5432
    #volumes:
    #  - ./docker-data/db:/var/lib/postgresql/data